fix(install): fallback to git command to retrieve latest ddb

diff --git a/installer b/installer
--- a/installer
+++ b/installer
@@ -131,6 +131,23 @@ DOCKER_DEVBOX_BIN_URL=$(curl -fsSL $DOCKER_DEVBOX_CURL_OPTS_GITHUB_API https://a
 | grep "browser_download_url.*/$DOCKER_DEVBOX_DDB_ASSET_NAME\"" \
 | cut -d : -f 2,3 \
 | tr -d \")
+
+if [[ -z "${DOCKER_DEVBOX_BIN_URL}" ]]; then
+  # Github API may fail, most commonly because of unauthenticated rate limit.
+  # Use git to retrieve latest release tag and build url manually.
+  DOCKER_DEVBOX_LATEST_RELEASE=$(git -c 'versionsort.suffix=-' \
+      ls-remote --exit-code --refs --sort='version:refname' --tags https://github.com/inetum-orleans/docker-devbox-ddb 'v*.*.*' \
+      | tail --lines=1 \
+      | cut --delimiter='/' --fields=3)
+
+  if [[ -z "${DOCKER_DEVBOX_BIN_URL}" ]]; then
+      echo "Can't find docker-devbox-ddb last release." 2>&1 | tee -a "$_LOG"
+      exit 1
+  fi
+
+  DOCKER_DEVBOX_BIN_URL="https://github.com/inetum-orleans/docker-devbox-ddb/releases/download/${DOCKER_DEVBOX_LATEST_RELEASE}/${DOCKER_DEVBOX_DDB_ASSET_NAME}"
+fi
+
 curl -fsSL -o "$DOCKER_DEVBOX_BIN/ddb" $DOCKER_DEVBOX_BIN_URL
 chmod +x "$DOCKER_DEVBOX_BIN/ddb"
 
